---
title: "Stat 159 Final Project - Providing Credit to Students"
author: "Young Hoon Kim, Yoon Jung Rho,Joseph Simonian, Ellen Hwang"
date: "December 2, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

## Abstract

The final project for Stat 159 consists of performing a virtual consulting data analysis project using data from College Scorecard. The underlying goal is to use all the computational tools and apply all the concepts covered in the course to create a computationally reproducible analysis. 

# Introduction

## Introduction
This is report, we are using the data from _College Scorecard_:

[https://collegescorecard.ed.gov/](https://collegescorecard.ed.gov/)

_College Scorecard_ is developed by the U.S. Department of Education (under Obama's Administration) to provide "key indicators about the cost and value of institutions across the country to help students choose a school that is well-suited to meet their needs, priced affordably, and is consistent with their educational and career goals". Read more in this [press release](http://www.ed.gov/news/press-releases/education-department-releases-college-scorecard-help-students-choose-best-college-them).

With the various documents and the available data, we want to look at reliable and unbiased information about college performance and perfrom a consulting project for our client.


## Introduction - cont

Here is the profile for our client:

- A credit institution that provides financial aid to students. The managers are interested in expanding their customer base but they would also like that most of the loans be payed back. Should they give credit to students attending any college? Should they give credit to students attending a university in which most students tend to find jobs after graduating?

# Data

## Data

The data from College Scorecard provide insights into the performance of schools eligible to receive federal financial aid, and offer a look at the outcomes of students at those schools. The Data that appear on the College Scorecard provides data on student completion, debt and repayment, earnings, and more. The files include data from 1996 through 2016 for all undergraduate degree-granting institutions of higher education. This data was last updated on September 13th, 2016. The data is available at:

[https://collegescorecard.ed.gov/data/](https://collegescorecard.ed.gov/data/)

## Data - cont

For our project, besides the main data, our team also used featured downloads provided by College Scorecard. These data downloads provide quick access to some of the data in which users may be most interested, including a file that offers the most current data for each element. Among variety of data, we used [Post-School earnings](https://ed-public-download.apps.cloud.gov/downloads/Most-Recent-Cohorts-Treasury-Elements.csv) to narrow down the analytical component.

There is also a documentation that provides more on how to use the data, including: Sources of the data, The construction of metrics, and Data considerations and limitations available at :
[https://collegescorecard.ed.gov/data/documentation/](https://collegescorecard.ed.gov/data/documentation/)

